apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: conmail-zookeeper
spec:
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  dataVolumeCapacity: 6Gi
  logVolumeCapacity: 5Gi
  storageClass:
    name: conmail-kafka-storage-class
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: conmail-kafka
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  dataVolumeCapacity: 7Gi
  storageClass:
    name: conmail-kafka-storage-class
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: conmail-schemaregistry
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.8.0
    init: confluentinc/confluent-init-container:2.10.0